[project]
name = "camspy"
version = "0.0.1"
description = "Camspy"
readme = "README.md"
requires-python = ">=3.13"
license = "MIT"
license-files = ["LICENSE*"]
dependencies = [
    "click>=8.3.1",
    "click-default-group>=1.2.4",
    "distro>=1.9.0",
    "imutils>=0.5.4",
    "numpy>=2.4.1",
    "opencv-python>=4.11.0.86",
    "picamera2>=0.3.33; sys_platform == 'linux'",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
    "schema>=0.7.8",
    "simple-pid>=2.0.1",
    "paramiko>=4.0.0",
    "python-dotenv>=1.2.1"
]
classifiers = [
    'Programming Language :: Python :: 3.13',
    'License :: OSI Approved :: MIT License',
    'Intended Audience :: Developers',
]
[project.urls]
Homepage = "https://github.com/vossenv/camspy"
Issues = "https://github.com/vossenv/camspy/issues"

[build-system]
requires = [
    "uv_build >= 0.9.26, <0.10.0"
]
build-backend = "uv_build"

[project.scripts]
camspy = "camspy.app:run"
camspy_install = "camspy.app:install"

#[tool.uv.build-backend]
## Assuming the module is under src/
#module-root = "src"
#module-name = "camspy"