env_path: '~/.camspy_env'
device:
  name: 'test_cam'
  arducam_registers:    # leave blank for defaults - AR0134_960p_Color.json
  camera: picam
  device_id: 0
  frame_size: [1200, 1200]
  init_delay: 1
  init_retry: 10
  max_error_rate: 5       # arducam only
  codec: h264           # only for picam-direct
  annotation_scale: 30  # picam-direct - 0 to disable
  flip_vertical: true
  flip_horizontal: true
connection:
  host: X
  name: default_cam
  timeout: 10
sftp:
  host: SF_HOST
  port: SF_PORT
  username: SF_USER
  password: SF_PASS
logging:
  filename: cam.log
  level: debug
  log_stdout: false               # Enables logging of sys.out and sys.err
  log_metrics: true
  ignore_warnings: true           # Data len etc
  log_extra_info: true
  log_dir: logs
recording:
  output_directory: video
  resolution: [1200,1200]
  max_video_file_size: 10                # megabytes
  bitrate: 3000 #kB/sec
  framerate: 30 # not works...
  data_bar: [0.8, 10]    # scale, padding
  show_fps: true
processing:
  record_video: true
  mjpeg_stream: true
  send_video: true


